### ISSUE TITLE
Code running abnormally

### ISSUE THREAD

**Issue by CoolCEO** [clarivate/wos_api_usecases#33]
I want to run main.py in the Citation Report for Larger Datasets
But it will report an error on line 53. I tried to check the final result, such as   print (initial_request), and the final result was <Response [512]>

I provided apikey according to your tutorial and did not make any changes to the code. After running it, I did not get normal results. How can I solve this problem?

**Comment by KasyanovPavel** [comment]
Hello CoolCEO. Sorry to hear you're experiencing issues with the script. Can you please share the search query that you've used?

Also, could you perhaps share name of the application with which you are registered on the Clarivate Developer portal? Would it be ok for you if I use the email associated with it to reach out to you directly?

Thank you.

**Comment by KasyanovPavel** [comment]
Hi @CoolCEO just wanted to check whether you've had a chance to read my previous answer and if you can share a search query that you've used so that I try to replicate the issue on my end?

Also, could you perhaps share name of the application with which you are registered on the Clarivate Developer portal? That would be the most secure way of sharing your email address with us if you are ok for us to reach out to you directly.

Thank you.

**Comment by KasyanovPavel** [comment]
Hello @CoolCEO, just wanted to check again if you're still experiencing the issue with the code.

If you need some more time to check it, please let us know.

Thank you.

**Comment by KasyanovPavel** [comment]
Hi @CoolCEO, i was still unable to replicate the issue on my side, I will close the issue for now, but if you find any time to share the query that you used to get that result, please feel free to add a new comment. Thank you.
